<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>



<div class="searchHomeContent">
<div class="row">
<div class="col-lg-12 placa-home-title">EXPLORA LAS PUBLICACIONES CIENT&Iacute;FICAS DE <br />AM&Eacute;RICA LATINA EN ACCESO ABIERTO</div>
</div>
<div class="row form-home"><form action="/vufind/Search/Results" autocomplete="on" method="get" name="searchForm" id="searchForm" class="form-inline">
<div class="col-lg-2 col-sm-12 no-padding">&nbsp;</div>
<div class="col-lg-4 col-sm-12 no-padding"><!--input id="searchForm_lookfor" class="form-control search-query searcher searchome" name="lookfor" type="text" value="" placeholder="Ingresar texto..." /--> <input name="lookfor" type="text" value="" id="searchForm_lookfor" class="searchForm_lookfor form-control search-query autocomplete searcher:Solr searchome" placeholder="Ingresar texto..." /></div>
<div class="col-lg-2 hidden-sm hidden-xs no-padding"><select name="type" id="searchForm_type" class="form-control selector" data-native-menu="false"><option value="AllFields">Todos los Campos</option><option value="Title">T&iacute;tulo</option><option value="Author">Autor</option><option value="Subject">Materia</option><option value="network_name_str">Pa&iacute;s</option></select></div>
<div class="col-lg-1 col-sm-12 no-padding"><button type="submit" id="submit-home" class="btn btn-primary buscarbtn">Buscar</button></div>
<div class="col-lg-1 col-sm-12 no-padding"><a href="vufind/Search/Advanced" id="advance-search" class="btn btn-link advanced">Avanzada</a></div>
<div class="col-lg-2 col-sm-12 no-padding">&nbsp;</div>
</form></div>
<div class="row">
<div class="col-lg-12 content-datos">

<script>

function addSeparator(nStr) {
    nStr += '';
    x = nStr.split(',');
    x1 = x[0];
    x2 = x.length > 1 ? ',' + x[1] : '';
    var rgx = /(\d+)(\d{3})/;
    while (rgx.test(x1)) {
        x1 = x1.replace(rgx, '$1' + '.' + '$2');
    }
    return x1 + x2;
}

    $.ajax({
      type: 'GET',
      url: '/api/vufind/search?type=AllFields&page=0&limit=0&lng=<?= $this->layout()->userLang ?>',
      success: function (data) {
        $('#totalRecords').html(addSeparator(data.resultCount));
      }
    });
    $.ajax({
      type: 'GET',
      url: '/api/vufind/search?type=AllFields&page=0&limit=0&lng=<?= $this->layout()->userLang ?>&facet[]=format',
      success: function (data) {
        var format = {};

        for (var i=0; i< data.facets.format.length; i++) {
          var facet = data.facets.format[i];
          format[ facet.value ] = facet.count;
        }


        $('#article').html(addSeparator(format['article']));
        $('#masterThesis').html(addSeparator(format['masterThesis']));
        $('#doctoralThesis').html(addSeparator(format['doctoralThesis']));
        $('#report').html(addSeparator(format['report']));

      }
    });
  </script>

<div class="col-lg-2 col-sm-12 no-padding">&nbsp;</div>
<div class="col-lg-2 boxslider no-padding dropdown">
<div class="box-blue dropdown-toggle" data-toggle="dropdown">
<h3><a href="nodos">9</a></h3>
<h4><a href="nodos">NODOS NACIONALES</a></h4>
</div>
<ul class="dropdown-menu">
<li><a href="vufind/Search/Results?lookfor=network_acronym%3AAR">Argentina</a></li>
<li><a href="vufind/Search/Results?lookfor=network_acronym%3ABR">Brasil</a></li>
<li><a href="vufind/Search/Results?lookfor=network_acronym%3ACL">Chile</a></li>
<li><a href="vufind/Search/Results?lookfor=network_acronym%3ACO">Colombia</a></li>
<li><a href="vufind/Search/Results?lookfor=network_acronym%3ACR">Costa Rica</a></li>
<li><a href="vufind/Search/Results?lookfor=network_acronym%3AEC">Ecuador</a></li>
<li><a href="vufind/Search/Results?lookfor=network_acronym%3ASV">El Salvador</a></li>
<li><a href="vufind/Search/Results?lookfor=network_acronym%3AMX">M&eacute;xico</a></li>
<li><a href="vufind/Search/Results?lookfor=network_acronym%3APE">Per&uacute;</a></li>
<!--li><a href="/vufind/Search/Results?lookfor=network_acronym%3AVE">Venezuela</a></li--></ul>
</div>

<div class="col-lg-2 boxslider no-padding">
<div class="box-blue-light">
<h3 id="totalRecords"></h3>
<h4><a href="vufind/Search/Results?lookfor=*%3A*">DOCUMENTOS</a></h4>
</div>
</div>
<div class="col-lg-2 boxslider no-padding">
<div class="box-blue">
<div class="col-lg-12 boxslider2">
<h4 id="article"></h4>
<h5><a href="vufind/Search/Results?lookfor=format%3Aarticle">ART&Iacute;CULOS</a></h5>
</div>
<div class="col-lg-12 boxslider2">
<h4 id="report"></h4>
<h5><a href="vufind/Search/Results?lookfor=format%3Areport">REPORTES</a></h5>
</div>
</div>
</div>
<div class="col-lg-2 boxslider no-padding">
<div class="box-blue-light ">
<div class="col-lg-12 boxslider2">
<h4 id="doctoralThesis"></h4>
<h5><a href="vufind/Search/Results?lookfor=format%3AdoctoralThesis">TESIS DE DOCTORADO</a></h5>
</div>
<div class="col-lg-12 boxslider2">
<h4 id="masterThesis"></h4>
<h5><a href="vufind/Search/Results?lookfor=format%3AmasterThesis">TESIS DE MAESTR&Iacute;A</a></h5>
</div>
</div>
</div>
<div class="col-lg-2 col-sm-12 no-padding">&nbsp;</div>
</div>
</div>
</div>

