<?php

$timeStampFile = '/tmp/timeStampExpires.txt';
$tokenFile = '/tmp/token.txt';
$timeStampRead = '';
$token = '';

if (file_exists($timeStampFile)) {
    $timeStampRead = file_get_contents($timeStampFile);    
}
else{
    $myfile = fopen($timeStampFile, "w") or die("Unable to open file!");
    $txt = "0";
    fwrite($myfile, $txt);
    fclose($myfile);
}

if (file_exists($tokenFile)) {
    $token = file_get_contents($tokenFile);
}
else{
    $myfile = fopen($tokenFile, "w") or die("Unable to open file!");
    $txt = "0";
    fwrite($myfile, $txt);
    fclose($myfile);
}

$currentDate = new DateTime();
$currentTimeStamp = $currentDate->getTimestamp();

if ($currentTimeStamp <= $timeStampRead) {
    
} 
else 
{
    $username = '5662690b-86c8-4724-8e1c-ff943a578978';
    $password = 'AOyPE8t0MvBTOXVf9ymnzdoG8fsl3YUgTc8jCRKKI47QBNE66Bld7vSK0aaY21JgFmGMbjLuLwtijK41htC0Rew';
    $url = 'https://aai.openaire.eu/oidc/token';
    $fields = array('grant_type' => 'client_credentials');
    $fields_string = http_build_query($fields);

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_USERPWD, "$username:$password");
    curl_setopt($ch, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $fields_string);
    curl_setopt($ch, CURLOPT_POST, true);
    $output = curl_exec($ch);
    curl_close($ch);

    $obj = json_decode($output);
    $token = $obj->{'access_token'};
    $type = $obj->{'token_type'};
    $expires_in = $obj->{'expires_in'};

    $renewDate = new DateTime();
    $renewTimeStamp = $renewDate->getTimestamp();
 
    $renewDate->add(new DateInterval('PT' . $expires_in . 'S'));
 
    file_put_contents($tokenFile, $token);
    file_put_contents($timeStampFile, $renewDate->getTimestamp());
    
}

//el oai_identifier requerido para la consulta a OpenAIRE se obtiene a través de la función del SOLRLAReferencia
$oaiIdentifier = $this->driver->getIdentifierOAI();
$authorization = "Authorization: Bearer " . $token;

//setup the request, you can also use CURLOPT_URL
$ch3 = curl_init('https://api-test.openaire.eu/search/api/publications?originalId=' . $oaiIdentifier);
// Returns the data/output as a string instead of raw data
curl_setopt($ch3, CURLOPT_RETURNTRANSFER, true);
//Set your auth headers
curl_setopt($ch3, CURLINFO_HEADER_OUT, true);
curl_setopt($ch3, CURLOPT_HTTPHEADER, array(
   'Content-Type: application/xml',
   'Authorization: Bearer ' . $token
   ));
// get stringified data/output. See CURLOPT_RETURNTRANSFER
$response = curl_exec($ch3);
// get info about the request
$info = curl_getinfo($ch3);
// close curl resource to free up system resources
curl_close($ch3);

//////////////////////////////////////////////////////////////////////////////////

libxml_use_internal_errors(true);

$simple = simplexml_load_string($response);

$total = 0;

//El XML tiene un nodo "total" el cual, si es igual a cero significa que el registro no ha sido cosechado aún por OpenAIRE
$total = $simple->xpath("//total")[0];

if ($total > 0) {

    //Para obtener el id deduplicado del registro en OpenAIRE Explore debe leerse el nodo dri:objIdentifier
    $simple->registerXPathNamespace('dri', 'http://www.driver-repository.eu/namespace/dri');
    $dedup = $simple->xpath('//dri:objIdentifier');
    $openAIRElink = "https://explore.openaire.eu/search/publication?articleId=" . $dedup[0];

?>
    <p>
        <h5><strong style="border-bottom: 2px solid #c15f33;">Este registro también se encuentra en:</strong></h5>
        <div class="hosts">
            <div class="instances">
                <div class="instance">
                    <a href=" <?= $openAIRElink ?> "><img class="tab-image" src="/vufind/themes/lareferencia/images/openaire_tab/logo-large-explore.png" alt="OpenAIRE icon"></a>
                </div>

                <?php
                $instances = $simple->xpath('//instance');
                $webResources = $simple->xpath('//webresource');
                $dataStructure = array();
                $dataStructure2 = array();

                if (count($instances) > 0) {
                ?><h5><strong style="border-bottom: 2px solid #c15f33;">Y en:</strong></h5><?php

                                                                                            foreach ($instances as $instance) {
                                                                                                $dataStructure[$instance->attributes()["id"]->__toString()] = $instance->hostedby->attributes()["name"]->__toString();
                                                                                            }

                                                                                            $count2 = 0;
                                                                                            foreach ($webResources as $webResource) {
                                                                                                $parent = $webResource->xpath("..")[0];
                                                                                                $dataStructure2[$count2] = array($parent->attributes()["id"]->__toString() => $webResource->url->__toString());
                                                                                                $count2++;
                                                                                            }

                                                                                            foreach ($dataStructure as $id => $hostname) {
                                                                                            ?>
                        <div class="instance">
                            <ul>
                                <?= $hostname ?>
                                <br>
                                <?php
                                                                                                for ($d = 0; $d < count($dataStructure2); $d++) {
                                                                                                    if (key($dataStructure2[$d]) ==  $id) {
                                ?><li><a href=" <?= current($dataStructure2[$d]) ?> "><?= current($dataStructure2[$d]) ?></a></li>
                                <?php
                                                                                                    }
                                                                                                }
                                ?>
                            </ul>
                        </div>
                <?php
                                                                                            }
                                                                                        }
                ?>
            </div>
        </div>
    </p>

    <p>
        <?php

        $relatedDocs = $simple->xpath('//rel');
        $relationType = $simple->xpath('//to');

        $recomendations = array();
        $relatedDocType = array();
        $recomendedLinks = array();
        $relatedCounter = 0;

        //Si existe al menos 1 elemento relacionado
        if (count($relatedDocs) > 0) {
        ?>
            <div class="related-items">
                <?php
                //Se recorren todos los "rels"
                for ($j = 0; $j < count($relatedDocs); $j++) {
                    if ($relationType[$j]->attributes()["class"] == "isAmongTopNSimilarDocuments") {  //si es de este tipo de relación se almacena
                        $recomendations[$relatedCounter] = $relatedDocs[$j]->title->__toString();  //se obtiene el título
                        $relatedDocType[$relatedCounter] = $relationType[$j]->attributes()["type"];  //se obtiene el tipo de documento
                        $recomendedLinks[$relatedCounter] = $relationType[$j]->__toString(); //se obtiene el enlace
                        $relatedCounter++;
                    }
                }

                if ($relatedCounter > 0) {
                ?>
                    <h5><strong style="border-bottom: 2px solid #c15f33;">Documentos relacionados:</strong></h5>
                    <ul>
                        <?php
                        //Se muestran como lista, haciendo un recorrido de los arreglos con la información almacenada para las relaciones que nos interesan
                        for ($k = 0; $k < count($recomendedLinks); $k++) {
                            if ($relatedDocType[$k] == "publication") {
                        ?>
                                <li>
                                    <div class="rel-item">
                                        <a href="https://explore.openaire.eu/search/publication?articleId=<?= $recomendedLinks[$k] ?>"><?= $recomendations[$k] ?></a>
                                        <!--img class="tab-bullet" src="/vufind/themes/lareferencia/images/openaire_tab/publication.png" alt="Publication"-->
                                    </div>
                                </li>

                        <?php   }
                        }
                        ?></ul><?php
                            }
                        }
                                ?>
            </div>
    </p>

<?php
} else {
?>
    <h5>EL registro no se encuentra en OpenAIRE</h5>
<?php
}
?>
