<footer role="contentinfo" class="hidden-print"> 
  <div class="container">
    <div class="row">
      <div class="col-md-12 copyright ">
        <div class="row">
          <div class="col-md-12 col-sm-12">
            <div class="custom">
              <p class="centered-footer">
                <img src="<?= $this->imageLink('logofooter.png') ?>" alt="LA Referencia">
              </p>
              <p class="centered-footer">
                <span id="cloake1737c8de59b337430caa82f24971593">
                  <a href="mailto:repositoriosla@gmail.com">repositoriosla@gmail.com</a>
                </span>
                <script type="text/javascript">
                  document.getElementById('cloake1737c8de59b337430caa82f24971593').innerHTML = '';
                  var prefix = '&#109;a' + 'i&#108;' + '&#116;o';
                  var path = 'hr' + 'ef' + '=';
                  var addye1737c8de59b337430caa82f24971593 = 'r&#101;p&#111;s&#105;t&#111;r&#105;&#111;sl&#97;' + '&#64;';
                  addye1737c8de59b337430caa82f24971593 = addye1737c8de59b337430caa82f24971593 + 'gm&#97;&#105;l' + '&#46;' + 'c&#111;m';
                  var addy_texte1737c8de59b337430caa82f24971593 = 'r&#101;p&#111;s&#105;t&#111;r&#105;&#111;sl&#97;' + '&#64;' + 'gm&#97;&#105;l' + '&#46;' + 'c&#111;m';
                  document.getElementById('cloake1737c8de59b337430caa82f24971593').innerHTML += '<a ' + path + '\'' + prefix + ':' + addye1737c8de59b337430caa82f24971593 + '\'>' + addy_texte1737c8de59b337430caa82f24971593 + '<\/a>';
                </script>
               | <a href="/joomla/es/preguntas-frecuentes" target="_blank">Preguntas Frecuentes</a>
              <?=$this->render("footer-nodes.phtml")?>
              </p>
              <p class="centered-footer">
                <a href="http://creativecommons.org/licenses/by/4.0/">
                <img class="license-footer" src="http://i.creativecommons.org/l/by/3.0/88x31.png" alt="by"></a>
                A menos que se indique lo contrario, todos los materiales producidos por LA Referencia tienen una<a href="http://creativecommons.org/licenses/by/4.0/"> licencia CC 4.0 Internacional</a></p>
              <p class="centered-footer""><a href="http://creativecommons.org/licenses/by/4.0/"></a></p></div>    
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>


<!--<footer class="hidden-print">-->
<!--  <div class="footer-container">-->
<!--    <div class="footer-column">-->
<!--      <p><strong><?=$this->transEsc('Search Options')?></strong></p>-->
<!--      <ul>-->
<!--        <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>-->
<!--        <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>-->
<!--      </ul>-->
<!--    </div>-->
<!--    <div class="footer-column">-->
<!--      <p><strong><?=$this->transEsc('Find More')?></strong></p>-->
<!--      <ul>-->
<!--        <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>-->
<!--        <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>-->
<!--        <li><a href="<?=$this->url('channels-home')?>"><?=$this->transEsc('channel_explore')?></a></li>-->
<!--    <li><a href="<?=$this->url('search-reserves')?>"><?=$this->transEsc('Course Reserves')?></a></li>-->
<!--        <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>-->
<!--      </ul>-->
<!--    </div>-->
<!--    <div class="footer-column">-->
<!--      <p><strong><?=$this->transEsc('Need Help?')?></strong></p>-->
<!--      <ul>-->
<!--        <li><a href="<?=$this->url('help-home')?>?topic=search&amp;_=<?=time() ?>" data-lightbox class="help-link"><?=$this->transEsc('Search Tips')?></a></li>-->
<!--        <li><a href="<?=$this->url('content-page', ['page' => 'asklibrary']) ?>"><?=$this->transEsc('Ask a Librarian')?></a></li>-->
<!--        <li><a href="<?=$this->url('content-page', ['page' => 'faq']) ?>"><?=$this->transEsc('FAQs')?></a></li>-->
<!--      </ul>-->
<!--    </div>-->
<!--  </div>-->
<!--  <div class="poweredby">-->
<!--    <?=$this->layout()->poweredBy ?>-->
<!--  </div>-->
<!--</footer>-->
