<script>
  (function (d, s, idScript, idRec, userInput) {
    var coreAddress = 'https://core.ac.uk/';
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(idScript)) return;
    js = d.createElement(s);
    js.id = idScript;
    js.src = coreAddress + 'recommender/embed.js';
    fjs.parentNode.insertBefore(js, fjs);

    localStorage.setItem('idRecommender', idRec);
    localStorage.setItem('userInput', JSON.stringify(userInput));

    var link = d.createElement('link');
    link.setAttribute('rel', 'stylesheet');
    link.setAttribute('type', 'text/css');
    link.setAttribute('href', coreAddress + 'recommender/embed-default-style.css');
    d.getElementsByTagName('head')[0].appendChild(link);
  }(document, 'script', 'recommender-embed', '599795', {}));
</script>

<h4 class="coreRecommenderTitle"> Contenido relacionado en CORE</h4>
<div style="width:100% !important;"  id="coreRecommenderOutput"><p>cargando ... espere un momento por favor.</p></div>
