<br>
<a href="http://repositoriosdigitales.mincyt.gob.ar:8380/dnet-web-generic/" target="_blank">Argentina</a>
| 
<a href="http://oasisbr.ibict.br/vufind/" target="_blank">Brasil</a>
| 
<a href="http://www.sic.informacioncientifica.cl/" target="_blank">Chile</a>
| 
<a href="http://190.242.114.6:8080/web/guest/inicio" target="_blank">Colombia</a>
| 
<a href="http://kimuk.conare.ac.cr/" target="_blank">Costa Rica</a>
| 
<a href="http://rraae.org.ec/" target="_blank">Ecuador</a>
| 
<a href="http://www.redicces.org.sv/jspui/" target="_blank">El Salvador</a>
| 
<a href="https://recolecta.fecyt.es/" target="_blank">España</a>
|
<a href="http://www.remeri.org.mx/portal/index.html" target="_blank">México</a>
|
<a href="http://alicia.concytec.gob.pe/vufind/" target="_blank">Perú</a>
|
<a href="https://silo.uy/vufind/" target="_blank">Uruguay</a>
